version: "3.4"
services:
  nginx:
    restart: always
    build: nginx/
    ports:
      - 5443:5443
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
    links:
      - web:web
    networks:
      - unw

  web:
    build: .
    environment:
      DATABASE_URL: "postgres://postgres:unleash@db/postgres"
      DATABASE_SSL: "false"
    depends_on:
      - db
    command: npm run start
    healthcheck:
      test: ["CMD", "nc",  "-z", "db", "5432"]
      interval: 1s
      timeout: 1m
      retries: 5
      start_period: 15s
    networks:
      - unw
  db:
    image: postgres:10-alpine
    environment:
      POSTGRES_DB: "db"
      POSTGRES_HOST_AUTH_METHOD: "trust"
    healthcheck:
      test: ["CMD", "pg_isready", "--username=postgres", "--host=127.0.0.1", "--port=5432"]
      interval: 2s
      timeout: 1m
      retries: 5
      start_period: 10s
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - unw

networks:
  unw:
