FROM arm64v8/node as builder

WORKDIR /unleash

COPY index.js package.json package-lock.json ./

RUN npm i
RUN npm ci

FROM arm64v8/node

ENV NODE_ENV production

WORKDIR /unleash

COPY --from=builder /unleash /unleash

EXPOSE 4242

USER node

CMD node index.js
